PR Comments

diff --git a/scripts/git-hooks/pre-commit b/scripts/git-hooks/pre-commit
--- a/scripts/git-hooks/pre-commit
+++ b/scripts/git-hooks/pre-commit
@@ -23,7 +23,7 @@ if [ $? != 0 ]; then
 	EXIT=1
 fi
 
-# Check that all files conform to Black.
+echo "Checking Black..."
 black --check development/ nautobot/ tasks.py
 if [[ $? != 0 ]]; then
     EXIT=1
@@ -36,8 +36,17 @@ if [ $? != 0 ]; then
 	EXIT=1
 fi
 
+HADOLINT_PATH=$(which hadolint)
+if [ -x $HADOLINT_PATH ]; then
+	echo "Checking Dockerfile..."
+	hadolint docker/Dockerfile
+	if [ $? != 0 ]; then
+		EXIT=1
+	fi
+fi
+
 if [ $EXIT != 0 ]; then
-  printf "${RED}COMMIT FAILED${NOCOLOR}\n"
+	printf "${RED}COMMIT FAILED${NOCOLOR}\n"
 fi
 
 exit $EXIT
