fix: CI integration workflow builds

diff --git a/.github/workflows/ci_integration.yml b/.github/workflows/ci_integration.yml
--- a/.github/workflows/ci_integration.yml
+++ b/.github/workflows/ci_integration.yml
@@ -7,38 +7,39 @@ on:  # yamllint disable
       - "main"
       - "develop"
       - "next"
-  workflow_call:
+      - "u/snaselj-4028-ci-integration-workflows"
+  workflow_call: {}
 
 jobs:
   black:
-    runs-on: "ubuntu-20.04"
+    runs-on: "ubuntu-22.04"
     env:
       INVOKE_NAUTOBOT_LOCAL: "True"
     steps:
       - name: "Check out repository code"
-        uses: "actions/checkout@v2"
+        uses: "actions/checkout@v3"
       - name: "Setup environment"
         uses: "networktocode/gh-action-setup-poetry-environment@v2"
       - name: "Linting: black"
         run: "poetry run invoke black"
   flake8:
-    runs-on: "ubuntu-20.04"
+    runs-on: "ubuntu-22.04"
     env:
       INVOKE_NAUTOBOT_LOCAL: "True"
     steps:
       - name: "Check out repository code"
-        uses: "actions/checkout@v2"
+        uses: "actions/checkout@v3"
       - name: "Setup environment"
         uses: "networktocode/gh-action-setup-poetry-environment@v2"
       - name: "Linting: flake8"
         run: "poetry run invoke flake8"
   markdownlint:
-    runs-on: "ubuntu-20.04"
+    runs-on: "ubuntu-22.04"
     env:
       INVOKE_NAUTOBOT_LOCAL: "True"
     steps:
       - name: "Check out repository code"
-        uses: "actions/checkout@v2"
+        uses: "actions/checkout@v3"
       - name: "Linting: markdownlint"
         uses: "nosborn/github-action-markdown-cli@v3.0.1"
         with:
@@ -47,18 +48,18 @@ jobs:
           ignore_files: "nautobot/project-static"
           rules: "scripts/use-relative-md-links.js"
   hadolint:
-    runs-on: "ubuntu-20.04"
+    runs-on: "ubuntu-22.04"
     env:
       INVOKE_NAUTOBOT_LOCAL: "True"
     steps:
       - name: "Check out repository code"
-        uses: "actions/checkout@v2"
+        uses: "actions/checkout@v3"
       - name: "Run Hadolint"
         uses: "hadolint/hadolint-action@v1.6.0"
         with:
           dockerfile: "docker/Dockerfile"
   check-migrations:
-    runs-on: "ubuntu-20.04"
+    runs-on: "ubuntu-22.04"
     env:
       INVOKE_NAUTOBOT_LOCAL: "True"
       NAUTOBOT_DB_USER: "nautobot"
@@ -75,7 +76,7 @@ jobs:
           - "5432:5432"
     steps:
       - name: "Check out repository code"
-        uses: "actions/checkout@v2"
+        uses: "actions/checkout@v3"
       - name: "Setup environment"
         uses: "networktocode/gh-action-setup-poetry-environment@v2"
       - name: "Run check migrations"
@@ -86,7 +87,7 @@ jobs:
       - "markdownlint"
       - "hadolint"
   check-schema:
-    runs-on: "ubuntu-20.04"
+    runs-on: "ubuntu-22.04"
     env:
       INVOKE_NAUTOBOT_LOCAL: "True"
       NAUTOBOT_DB_USER: "nautobot"
@@ -104,7 +105,7 @@ jobs:
           - "5432:5432"
     steps:
       - name: "Check out repository code"
-        uses: "actions/checkout@v2"
+        uses: "actions/checkout@v3"
       - name: "Setup environment"
         uses: "networktocode/gh-action-setup-poetry-environment@v2"
       - name: "Run check-schema"
@@ -117,7 +118,7 @@ jobs:
       - "hadolint"
 
   pylint:
-    runs-on: "ubuntu-20.04"
+    runs-on: "ubuntu-22.04"
     env:
       INVOKE_NAUTOBOT_LOCAL: "True"
       NAUTOBOT_DB_USER: "nautobot"
@@ -135,7 +136,7 @@ jobs:
           - "5432:5432"
     steps:
       - name: "Check out repository code"
-        uses: "actions/checkout@v2"
+        uses: "actions/checkout@v3"
       - name: "Setup environment"
         uses: "networktocode/gh-action-setup-poetry-environment@v2"
       - name: "Run pylint"
@@ -145,7 +146,7 @@ jobs:
       - "check-schema"
 
   tests-postgres:
-    runs-on: "ubuntu-20.04"
+    runs-on: "ubuntu-22.04"
     strategy:
       fail-fast: true
       matrix:
@@ -170,7 +171,7 @@ jobs:
           - "6379:6379"
     steps:
       - name: "Check out repository code"
-        uses: "actions/checkout@v2"
+        uses: "actions/checkout@v3"
       - name: "Setup environment"
         uses: "networktocode/gh-action-setup-poetry-environment@v2"
         with:
@@ -188,7 +189,7 @@ jobs:
       - "check-schema"
 
   tests-mysql:
-    runs-on: "ubuntu-20.04"
+    runs-on: "ubuntu-22.04"
     strategy:
       fail-fast: true
       matrix:
@@ -215,7 +216,7 @@ jobs:
           - "6379:6379"
     steps:
       - name: "Check out repository code"
-        uses: "actions/checkout@v2"
+        uses: "actions/checkout@v3"
       - name: "Setup environment"
         uses: "networktocode/gh-action-setup-poetry-environment@v2"
         with:
@@ -237,7 +238,7 @@ jobs:
       - "check-schema"
 
   integration-test:
-    runs-on: "ubuntu-20.04"
+    runs-on: "ubuntu-22.04"
     env:
       INVOKE_NAUTOBOT_LOCAL: "True"
       NAUTOBOT_DB_USER: "nautobot"
@@ -263,7 +264,7 @@ jobs:
           - "4444:4444"
     steps:
       - name: "Check out repository code"
-        uses: "actions/checkout@v2"
+        uses: "actions/checkout@v3"
       - name: "Setup environment"
         uses: "networktocode/gh-action-setup-poetry-environment@v2"
       - name: "Remove Installed Nautobots (Poetry Workaround)" # Workaround for https://github.com/python-poetry/poetry/issues/2918
@@ -282,92 +283,72 @@ jobs:
 
   container-build:
     name: "Build Container Images (GHCR Only)"
-    runs-on: "ubuntu-20.04"
+    runs-on: "ubuntu-22.04"
     if: "github.event_name == 'push' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/next')"
     needs:
       - "integration-test"
-    strategy:
-      fail-fast: true
-      matrix:
-        python-version: [ "3.7", "3.8", "3.9", "3.10" ]
-    env:
-      INVOKE_NAUTOBOT_PYTHON_VER: "${{ matrix.python-version }}"
     steps:
+      - name: "Configuration"
+        id: "config"
+        shell: "bash"
+        run: |
+          ref="${{ github.ref }}"
+          branch="${ref#refs/heads/}"
+
+          case "$branch" in
+            "develop")
+              min_python_version="3.7"
+              max_python_version="3.10"
+              ;;
+            "next")
+              min_python_version="3.8"
+              max_python_version="3.11"
+              ;;
+            *)
+              echo "Invalid branch $branch"
+              exit 1
+              ;;
+          esac
+
+          echo "branch=$branch" >> $GITHUB_OUTPUT
+          echo "min-python-version=$min_python_version" >> $GITHUB_OUTPUT
+          echo "max-python-version=$max_python_version" >> $GITHUB_OUTPUT
       - name: "Check out repository code"
-        uses: "actions/checkout@v2"
-      - run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
-        id: "gitbranch"
+        uses: "actions/checkout@v3"
       - name: "Set up QEMU"
-        uses: "docker/setup-qemu-action@v1"
+        uses: "docker/setup-qemu-action@v2"
       - name: "Set up Docker Buildx"
-        uses: "docker/setup-buildx-action@v1"
-      - name: Login to GitHub Container Registry
-        uses: docker/login-action@v1
+        uses: "docker/setup-buildx-action@v2"
+      - name: "Login to GitHub Container Registry"
+        uses: "docker/login-action@v2"
         with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-      - name: "Docker Metadata"
-        id: "dockermeta"
-        uses: "docker/metadata-action@v3"
+          registry: "ghcr.io"
+          username: "${{ github.actor }}"
+          password: "${{ secrets.GITHUB_TOKEN }}"
+      - name: "Build `final` Max"
+        uses: "./.github/actions/build-nautobot-image"
         with:
-          images: "ghcr.io/nautobot/nautobot"
-          flavor: |
-            latest=false
-          tags: |
-            type=raw,value={{branch}}-py${{ matrix.python-version }}
-            type=raw,value={{branch}}-{{sha}}-{{date 'X'}}-py${{ matrix.python-version }}
-            type=raw,value={{branch}},enable=${{ matrix.python-version == 3.7 }}
-            type=raw,value={{branch}}-{{sha}}-{{date 'X'}},enable=${{ matrix.python-version == 3.7 }}
-            type=raw,value=latest,enable=${{ matrix.python-version == 3.7 && github.ref == 'refs/heads/develop' }}
-            type=raw,value=latest-py${{ matrix.python-version }},enable=${{ github.ref == 'refs/heads/develop' }}
-          labels: |
-            org.opencontainers.image.title=Nautobot
-      - name: "Build"
-        uses: "docker/build-push-action@v2"
+          branch: "${{ steps.config.outputs.branch }}"
+          image: "ghcr.io/nautobot/nautobot"
+          latest: false
+          push: false
+          python-version: "${{ steps.config.outputs.max-python-version }}"
+          target: "final"
+      - name: "Build `final-dev` Min"
+        uses: "./.github/actions/build-nautobot-image"
         with:
+          branch: "${{ steps.config.outputs.branch }}"
+          image: "ghcr.io/nautobot/nautobot-dev"
+          latest: true
           push: true
-          target: final
-          file: "docker/Dockerfile"
-          platforms: "linux/amd64,linux/arm64"
-          tags: "${{ steps.dockermeta.outputs.tags }}"
-          labels: "${{ steps.dockermeta.outputs.labels }}"
-          cache-from: "type=gha,scope=nautobot-${{ steps.gitbranch.outputs.branch }}-${{ matrix.python-version }}"
-          cache-to: "type=gha,mode=max,scope=nautobot-${{ steps.gitbranch.outputs.branch }}-${{ matrix.python-version }}"
-          context: "."
-          build-args: |
-            PYTHON_VER=${{ matrix.python-version }}
-            DEPENDENCIES_BASE_BRANCH=${{ steps.gitbranch.outputs.branch }}
-            POETRY_PARALLEL=true
-      - name: "Docker Dev Metadata"
-        id: "dockerdevmeta"
-        uses: "docker/metadata-action@v3"
+          python-version: "${{ steps.config.outputs.min-python-version }}"
+          target: "final-dev"
+      - name: "Build `final-dev` Max"
+        uses: "./.github/actions/build-nautobot-image"
         with:
-          images: "ghcr.io/nautobot/nautobot-dev"
-          flavor: |
-            latest=false
-          tags: |
-            type=raw,value={{branch}}-py${{ matrix.python-version }}
-            type=raw,value={{branch}}-{{sha}}-{{date 'X'}}-py${{ matrix.python-version }}
-            type=raw,value={{branch}},enable=${{ matrix.python-version == 3.7 }}
-            type=raw,value={{branch}}-{{sha}}-{{date 'X'}},enable=${{ matrix.python-version == 3.7 }}
-            type=raw,value=latest,enable=${{ matrix.python-version == 3.7 && github.ref == 'refs/heads/develop' }}
-            type=raw,value=latest-py${{ matrix.python-version }},enable=${{ github.ref == 'refs/heads/develop' }}
-          labels: |
-            org.opencontainers.image.title=Nautobot
-      - name: "Build Dev Containers"
-        uses: "docker/build-push-action@v2"
-        with:
+          branch: "${{ steps.config.outputs.branch }}"
+          image: "ghcr.io/nautobot/nautobot-dev"
+          latest: false
           push: true
-          target: final-dev
-          file: "docker/Dockerfile"
-          platforms: "linux/amd64,linux/arm64"
-          tags: "${{ steps.dockerdevmeta.outputs.tags }}"
-          labels: "${{ steps.dockerdevmeta.outputs.labels }}"
-          cache-from: "type=gha,scope=nautobot-${{ steps.gitbranch.outputs.branch }}-${{ matrix.python-version }}"
-          cache-to: "type=gha,mode=max,scope=nautobot-${{ steps.gitbranch.outputs.branch }}-${{ matrix.python-version }}"
-          context: "."
-          build-args: |
-            PYTHON_VER=${{ matrix.python-version }}
-            DEPENDENCIES_BASE_BRANCH=${{ steps.gitbranch.outputs.branch }}
-            POETRY_PARALLEL=true
+          python-version: "${{ steps.config.outputs.max-python-version }}"
+          target: "final-dev"
